/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/errorBoundary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/baseApi`; params?: Router.UnknownInputParams; } | { pathname: `/api/productApi`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorState`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageCarousel`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCardSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductDetailSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/navigator/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductDetail`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/store`; params?: Router.UnknownInputParams; } | { pathname: `/store/slices/favoritesSlice`; params?: Router.UnknownInputParams; } | { pathname: `/store/slices/productsSlice`; params?: Router.UnknownInputParams; } | { pathname: `/types/guards`; params?: Router.UnknownInputParams; } | { pathname: `/types/product`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/errorBoundary`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/api/baseApi`; params?: Router.UnknownOutputParams; } | { pathname: `/api/productApi`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ErrorState`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ImageCarousel`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProductCardSkeleton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProductDetailSkeleton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/navigator/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ProductDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ProductList`; params?: Router.UnknownOutputParams; } | { pathname: `/store`; params?: Router.UnknownOutputParams; } | { pathname: `/store/slices/favoritesSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/store/slices/productsSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/types/guards`; params?: Router.UnknownOutputParams; } | { pathname: `/types/product`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/errorBoundary${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/api/baseApi${`?${string}` | `#${string}` | ''}` | `/api/productApi${`?${string}` | `#${string}` | ''}` | `/components/ErrorState${`?${string}` | `#${string}` | ''}` | `/components/ImageCarousel${`?${string}` | `#${string}` | ''}` | `/components/ProductCard${`?${string}` | `#${string}` | ''}` | `/components/ProductCardSkeleton${`?${string}` | `#${string}` | ''}` | `/components/ProductDetailSkeleton${`?${string}` | `#${string}` | ''}` | `/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/navigator/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/ProductDetail${`?${string}` | `#${string}` | ''}` | `/screens/ProductList${`?${string}` | `#${string}` | ''}` | `/store${`?${string}` | `#${string}` | ''}` | `/store/slices/favoritesSlice${`?${string}` | `#${string}` | ''}` | `/store/slices/productsSlice${`?${string}` | `#${string}` | ''}` | `/types/guards${`?${string}` | `#${string}` | ''}` | `/types/product${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/errorBoundary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/baseApi`; params?: Router.UnknownInputParams; } | { pathname: `/api/productApi`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorState`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageCarousel`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCardSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductDetailSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/navigator/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductDetail`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/store`; params?: Router.UnknownInputParams; } | { pathname: `/store/slices/favoritesSlice`; params?: Router.UnknownInputParams; } | { pathname: `/store/slices/productsSlice`; params?: Router.UnknownInputParams; } | { pathname: `/types/guards`; params?: Router.UnknownInputParams; } | { pathname: `/types/product`; params?: Router.UnknownInputParams; };
    }
  }
}
